export type discord_api_user_t = {
  id: string,
  username: string,
  avatar: string,
  discriminator: string,
  public_flags: number,
  flags: number,
  banner: any,
  accent_color: number,
  global_name: string,
  avatar_decoration_data: any,
  collectibles: any,
  banner_color: string,
  clan: any,
  primary_guild: any,
  mfa_enabled: boolean,
  locale: string,
  premium_type: number
}

export type github_api_user_t = {
    login: string,
    id: number,
    node_id: string,
    avatar_url: string,
    gravatar_id: string,
    url: string,
    html_url: string,
    followers_url: string,
    following_url: string,
    gists_url: string,
    starred_url: string,
    subscriptions_url: string,
    organizations_url: string,
    repos_url: string,
    events_url: string,
    received_events_url: string,
    type: string,
    user_view_type: string,
    site_admin: false,
    name: string,
    company: any,
    blog: string,
    location: string,
    email: string,
    hireable: any,
    bio: string,
    twitter_username: any,
    notification_email: string,
    public_repos: number,
    public_gists: number,
    followers: number,
    following: number,
    created_at: string,
    updated_at: string
  }